### ISSUE TITLE
Aisler.net shows warning on shortened pads

### ISSUE THREAD

**Issue by db6edr** [DG1JAN/UniBalun#3]
Hi Jan,

I've just uploaded the UnUn_BNC/UnUn_BNC.kicad_pcb to Aisler.net. Their board inspector gives a remark on some shortened pads. As I'm not used to creating / fabricating PCBs: is that as expected? Or does this require fixing?

![image](https://user-images.githubusercontent.com/264334/216657164-ec6fbe79-8ea1-4699-9389-bbcb3eac977b.png)

73 de Dirk DB6EDR

**Comment by DG1JAN** [comment]
Hello Dirk,

Thanks for the hint! This is a non functional issue, due to my manual editing of the PCB (out of the UniBalun File). 
Didn't checked it, because I ordered at JLCPB using gerber files.

I have updated the Net classes in the pcb file, so the Error from Aisler.net should be gone.

73 de Jan, DG1JAN

**Comment by db6edr** [comment]
Just checked, the error is gone.

Thanks!
